version: '3.8'
services:
  redis-test:
    image: redis:7-alpine
    ports:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - testnet

  zookeeper-test:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - testnet

  kafka-test:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092"
    depends_on:
      - zookeeper-test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-test:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - testnet

  mysql-test-master:
    image: mysql:8.0
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=grindelwald
      - MYSQL_REPLICATION_USER=test
      - MYSQL_REPLICATION_PASSWORD=test
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=grindelwald
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql-test-master/:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/00-init-master.sql
      - ./init/default-member.sql:/docker-entrypoint-initdb.d/01-default-member.sql
    networks:
      - testnet

  mysql-test-slave:
    image: mysql:8.0
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=grindelwald
      - MYSQL_REPLICATION_USER=test
      - MYSQL_REPLICATION_PASSWORD=test
    command:
      --server-id=2
      --relay-log=relay-log
      --log-bin=mysql-bin
      --read-only=ON
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --default-authentication-plugin=mysql_native_password
    depends_on:
      - mysql-test-master
    volumes:
      - ./data/mysql-test-slave/:/var/lib/mysql
      - ./init/test/init-slave.sh:/docker-entrypoint-initdb.d/00-init-slave.sh
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
